Create Table mvtHospCadPac(
codPaciente int identity primary key,
sexoPaciente varchar(1) not null,
dataNascPaciente datetime,
nomePaciente varchar(200),
nomeMaePaciente varchar(200),
cpfPaciente varchar(14),
rgPaciente varchar(50),
corPaciente varchar(50) not null,
nacionalidade varchar(50),
naturalidade varchar(50),
grauDeInstrucao varchar(50),
profissao varchar(200),
responsavel varchar(200),
cep varchar(9),
bairro varchar(200),
cidade varchar(200),
telefone varchar(13),
telefoneCelular varchar(13),
uf varchar(2),
rua varchar(50),
contatoAlternativo varchar(200),
telefoneContatoAlternativo varchar(13),
emailPaciente varchar(200),
oberservacaoPaciente varchar(2000),
situacao varchar(20),
numero int
);
